/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BeutifulSalon.view.modais;

import BeutifulSalon.Ferramentas.ManipulaFontes;
import BeutifulSalon.Ferramentas.Valida;
import BeutifulSalon.controller.CabeleireiroController;
import BeutifulSalon.dao.ExceptionDAO;
import BeutifulSalon.model.Cabeleireiro;
import BeutifulSalon.model.Observado;
import BeutifulSalon.model.Observador;
import java.awt.Font;
import java.awt.HeadlessException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.ResolverStyle;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author mateus
 */
public class modalExpediente extends javax.swing.JFrame implements Observado {

    ArrayList<Observador> observadores = new ArrayList<>();
    ArrayList<JFormattedTextField> horarios = new ArrayList<>();

    /**
     * Creates new form modalExpediente
     */
    public modalExpediente() {
        initComponents();
        
        ManipulaFontes mf = new ManipulaFontes();
        jLabel10.setFont(mf.getFont(mf.MEDIUM, Font.BOLD, 22f)); //Configure seu expediente
        jLabel1.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //Entrada
        jLabel2.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //Saída
        jLabel3.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //2a
        jLabel5.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //3a
        jLabel4.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //4a
        jLabel7.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //5a
        jLabel6.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //6a
        jLabel9.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //sab
        jLabel8.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //dom
        jButton1.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //Confirmar

        
        CabeleireiroController cc = new CabeleireiroController();
       DateTimeFormatter parserHora = DateTimeFormatter.ofPattern("HHmm");
 
            if (cc.verificaRegistro() == 1) {
                Cabeleireiro c = cc.selecionaCabeleireiro();
                
                jFTSegundaEntrada.setText(c.getSegundaE().format(parserHora));
                jFTSegundaSaida.setText(c.getSegundaS().format(parserHora));
                jFTTercaEntrada.setText(c.getTercaE().format(parserHora));
                jFTTercaSaida.setText(c.getTercaS().format(parserHora));
                jFTQuartaEntrada.setText(c.getQuartaE().format(parserHora));
                jFTQuartaSaida.setText(c.getQuartaS().format(parserHora));
                jFTQuintaEntrada.setText(c.getQuintaE().format(parserHora));
                jFTQuintaSaida.setText(c.getQuintaS().format(parserHora));
                jFTSextaEntrada.setText(c.getSextaE().format(parserHora));
                jFTSextaSaida.setText(c.getSextaS().format(parserHora));
                jFTSabadoEntrada.setText(c.getSabadoE().format(parserHora));
                jFTSabadoSaida.setText(c.getSabadoS().format(parserHora));
                jFTDomingoEntrada.setText(c.getDomingoE().format(parserHora));
                jFTDomingoSaida.setText(c.getDomingoS().format(parserHora));
            }


        horarios.add(jFTSegundaEntrada);
        horarios.add(jFTSegundaSaida);
        horarios.add(jFTTercaEntrada);
        horarios.add(jFTTercaSaida);
        horarios.add(jFTQuartaEntrada);
        horarios.add(jFTQuartaSaida);
        horarios.add(jFTQuintaEntrada);
        horarios.add(jFTQuintaSaida);
        horarios.add(jFTSextaEntrada);
        horarios.add(jFTSextaSaida);
        horarios.add(jFTSabadoEntrada);
        horarios.add(jFTSabadoSaida);
        horarios.add(jFTDomingoEntrada);
        horarios.add(jFTDomingoSaida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFTSegundaEntrada = new javax.swing.JFormattedTextField();
        jFTSegundaSaida = new javax.swing.JFormattedTextField();
        jFTTercaEntrada = new javax.swing.JFormattedTextField();
        jFTTercaSaida = new javax.swing.JFormattedTextField();
        jFTQuartaEntrada = new javax.swing.JFormattedTextField();
        jFTQuintaEntrada = new javax.swing.JFormattedTextField();
        jFTSextaEntrada = new javax.swing.JFormattedTextField();
        jFTSabadoEntrada = new javax.swing.JFormattedTextField();
        jFTDomingoEntrada = new javax.swing.JFormattedTextField();
        jFTDomingoSaida = new javax.swing.JFormattedTextField();
        jFTQuartaSaida = new javax.swing.JFormattedTextField();
        jFTQuintaSaida = new javax.swing.JFormattedTextField();
        jFTSextaSaida = new javax.swing.JFormattedTextField();
        jFTSabadoSaida = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(36, 46, 65));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Configure seu expediente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel3.setText("Segunda");

        jLabel5.setText("Terça");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entrada");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Saída");

        try {
            jFTSegundaEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTSegundaEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTSegundaEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFTSegundaEntrada.setPreferredSize(new java.awt.Dimension(38, 26));

        try {
            jFTSegundaSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTSegundaSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTSegundaSaida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            jFTTercaEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTTercaEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTTercaEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFTTercaEntrada.setPreferredSize(new java.awt.Dimension(38, 26));

        try {
            jFTTercaSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTTercaSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTTercaSaida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            jFTQuartaEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTQuartaEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTQuartaEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFTQuartaEntrada.setPreferredSize(new java.awt.Dimension(38, 26));

        try {
            jFTQuintaEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTQuintaEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTQuintaEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFTQuintaEntrada.setPreferredSize(new java.awt.Dimension(38, 26));

        try {
            jFTSextaEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTSextaEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTSextaEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFTSextaEntrada.setPreferredSize(new java.awt.Dimension(38, 26));

        try {
            jFTSabadoEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTSabadoEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTSabadoEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFTSabadoEntrada.setPreferredSize(new java.awt.Dimension(38, 26));

        try {
            jFTDomingoEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTDomingoEntrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTDomingoEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFTDomingoEntrada.setPreferredSize(new java.awt.Dimension(38, 26));

        try {
            jFTDomingoSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTDomingoSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTDomingoSaida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            jFTQuartaSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTQuartaSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTQuartaSaida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            jFTQuintaSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTQuintaSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTQuintaSaida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            jFTSextaSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTSextaSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTSextaSaida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            jFTSabadoSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTSabadoSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFTSabadoSaida.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Quinta");

        jLabel6.setText("Sexta");

        jLabel9.setText("Sábado");

        jLabel8.setText("Domingo");

        jLabel4.setText("Quarta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jFTSegundaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFTSegundaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jFTDomingoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFTDomingoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFTQuintaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jFTSextaEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jFTSabadoEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jFTQuartaEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jFTTercaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFTTercaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTQuartaSaida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTQuintaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTSextaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTSabadoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTSegundaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTSegundaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTTercaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTTercaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTQuartaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTSabadoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTQuintaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTSextaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTSextaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFTQuintaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFTSabadoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTQuartaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFTDomingoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFTDomingoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       notificarObservadores();

      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modalExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modalExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modalExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modalExpediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modalExpediente().setVisible(true);
            }
        });
    }

    public ArrayList<LocalTime> retornaHorarios() {

        ArrayList<LocalTime> expediente = new ArrayList<>();
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("HH:mm").withResolverStyle(ResolverStyle.STRICT);

        try {
            for (JFormattedTextField t : horarios) {
                
                String hora = t.getText();
                if (!hora.equals("") && Valida.isHora(hora)) {
                    try {
                        LocalTime h = LocalTime.parse(hora, formatador);
                        expediente.add(h);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                } else {
                    expediente.clear();
                    JOptionPane.showMessageDialog(null, "Verifique os horários inseridos e tente novamente.");
                    break;
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        return expediente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFTDomingoEntrada;
    private javax.swing.JFormattedTextField jFTDomingoSaida;
    private javax.swing.JFormattedTextField jFTQuartaEntrada;
    private javax.swing.JFormattedTextField jFTQuartaSaida;
    private javax.swing.JFormattedTextField jFTQuintaEntrada;
    private javax.swing.JFormattedTextField jFTQuintaSaida;
    private javax.swing.JFormattedTextField jFTSabadoEntrada;
    private javax.swing.JFormattedTextField jFTSabadoSaida;
    private javax.swing.JFormattedTextField jFTSegundaEntrada;
    private javax.swing.JFormattedTextField jFTSegundaSaida;
    private javax.swing.JFormattedTextField jFTSextaEntrada;
    private javax.swing.JFormattedTextField jFTSextaSaida;
    private javax.swing.JFormattedTextField jFTTercaEntrada;
    private javax.swing.JFormattedTextField jFTTercaSaida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void registrarObservador(Observador observador) {
        observadores.add(observador);
    }

    @Override
    public void removeObservador(Observador observador) {
        observadores.remove(observador);
    }

    @Override
    public void notificarObservadores() {
        
        ArrayList<LocalTime> expediente = retornaHorarios();
        observadores.forEach(ob -> ob.update(expediente));   
        this.dispose();
    }
}
