/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BeutifulSalon.view;

import BeutifulSalon.controller.ClienteController;
import BeutifulSalon.controller.OrcamentoController;
import BeutifulSalon.dao.ExceptionDAO;
import BeutifulSalon.model.Cliente;
import BeutifulSalon.model.Dinheiro;
import BeutifulSalon.model.Orcamento;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Mateus
 */
public class ApresentaFinancas extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    // IMPLEMENTANDO SISTEMA DE FECHAR E ABRIR TELA
    
    private MainMenu telaChamadoraMainMenu = null;
    private ApresentaCliente telaChamadoraApresentaCliente = null;
    
    public ApresentaFinancas() {
        initComponents();
    }
    
    //Chamando a partir de MainMenu
    public ApresentaFinancas(MainMenu aThis) {
        this.telaChamadoraMainMenu = aThis;
        telaChamadoraMainMenu.setVisible(false);
        try {          
           this.setPreferredSize(aThis.getSize());
        } catch (Exception e) {
            
        }
       
        initComponents();
    }
    
    //Chamando a partir de Cliente
    public ApresentaFinancas(ApresentaCliente aCliente){
        this.telaChamadoraApresentaCliente = aCliente;
        
        try {
            this.setPreferredSize(aCliente.getSize());
        } catch (Exception e) {
        }
        
        initComponents();
    }
    
    


    
    //============================//
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        menuLateral = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        gridLateral = new javax.swing.JPanel();
        panelDashboard = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        panelClientes = new javax.swing.JPanel();
        jTFClientes = new javax.swing.JLabel();
        panelProdutos = new javax.swing.JPanel();
        JTFProdutos = new javax.swing.JLabel();
        panelFinancas = new javax.swing.JPanel();
        JTFFinancas = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        panelNovoRegistro = new javax.swing.JPanel();
        JTFNovoRegistro = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConsultaOrcamento = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabelSearch = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAno = new javax.swing.JFormattedTextField();

        jLabel8.setText("jLabel8");

        setTitle("Finanças");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fecharJanela(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuLateral.setBackground(new java.awt.Color(36, 46, 66));
        menuLateral.setPreferredSize(new java.awt.Dimension(300, 500));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        gridLateral.setBackground(new java.awt.Color(36, 46, 66));
        gridLateral.setLayout(new java.awt.GridLayout(8, 0));

        panelDashboard.setBackground(new java.awt.Color(36, 46, 66));
        panelDashboard.setPreferredSize(new java.awt.Dimension(50, 200));

        dashboard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconHome.png"))); // NOI18N
        dashboard.setLabelFor(container);
        dashboard.setText("Dashboard");
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.setIconTextGap(20);
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDashboard(evt);
            }
        });

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDashboardLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridLateral.add(panelDashboard);

        panelClientes.setBackground(new java.awt.Color(36, 46, 66));
        panelClientes.setPreferredSize(new java.awt.Dimension(50, 200));

        jTFClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTFClientes.setForeground(new java.awt.Color(255, 255, 255));
        jTFClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconPeoples.png"))); // NOI18N
        jTFClientes.setText("Clientes");
        jTFClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTFClientes.setIconTextGap(16);

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jTFClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridLateral.add(panelClientes);

        panelProdutos.setBackground(new java.awt.Color(36, 46, 66));
        panelProdutos.setPreferredSize(new java.awt.Dimension(50, 200));

        JTFProdutos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JTFProdutos.setForeground(new java.awt.Color(255, 255, 255));
        JTFProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconPrice.png"))); // NOI18N
        JTFProdutos.setText("Produtos");
        JTFProdutos.setIconTextGap(20);

        javax.swing.GroupLayout panelProdutosLayout = new javax.swing.GroupLayout(panelProdutos);
        panelProdutos.setLayout(panelProdutosLayout);
        panelProdutosLayout.setHorizontalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProdutosLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(JTFProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelProdutosLayout.setVerticalGroup(
            panelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTFProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridLateral.add(panelProdutos);

        panelFinancas.setBackground(new java.awt.Color(36, 46, 66));
        panelFinancas.setPreferredSize(new java.awt.Dimension(50, 200));

        JTFFinancas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JTFFinancas.setForeground(new java.awt.Color(255, 255, 255));
        JTFFinancas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconWallet.png"))); // NOI18N
        JTFFinancas.setText("Finanças");
        JTFFinancas.setIconTextGap(20);

        javax.swing.GroupLayout panelFinancasLayout = new javax.swing.GroupLayout(panelFinancas);
        panelFinancas.setLayout(panelFinancasLayout);
        panelFinancasLayout.setHorizontalGroup(
            panelFinancasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFinancasLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(JTFFinancas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFinancasLayout.setVerticalGroup(
            panelFinancasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFinancasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTFFinancas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridLateral.add(panelFinancas);

        jPanel10.setBackground(new java.awt.Color(36, 46, 66));
        jPanel10.setPreferredSize(new java.awt.Dimension(50, 200));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        gridLateral.add(jPanel10);

        jPanel9.setBackground(new java.awt.Color(36, 46, 66));
        jPanel9.setPreferredSize(new java.awt.Dimension(50, 200));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        gridLateral.add(jPanel9);

        panelNovoRegistro.setBackground(new java.awt.Color(36, 46, 66));
        panelNovoRegistro.setPreferredSize(new java.awt.Dimension(50, 200));

        JTFNovoRegistro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JTFNovoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        JTFNovoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconAdd.png"))); // NOI18N
        JTFNovoRegistro.setText("Novo Registro");
        JTFNovoRegistro.setIconTextGap(20);
        JTFNovoRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNovoRegistro(evt);
            }
        });

        javax.swing.GroupLayout panelNovoRegistroLayout = new javax.swing.GroupLayout(panelNovoRegistro);
        panelNovoRegistro.setLayout(panelNovoRegistroLayout);
        panelNovoRegistroLayout.setHorizontalGroup(
            panelNovoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNovoRegistroLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(JTFNovoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNovoRegistroLayout.setVerticalGroup(
            panelNovoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNovoRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTFNovoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridLateral.add(panelNovoRegistro);

        javax.swing.GroupLayout menuLateralLayout = new javax.swing.GroupLayout(menuLateral);
        menuLateral.setLayout(menuLateralLayout);
        menuLateralLayout.setHorizontalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gridLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLateralLayout.setVerticalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(gridLateral, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
        );

        getContentPane().add(menuLateral, java.awt.BorderLayout.LINE_START);

        container.setBackground(new java.awt.Color(243, 244, 245));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 34, 34));
        jLabel2.setText("Confira o orçamento previsto do seu salão");

        jLabel1.setBackground(new java.awt.Color(34, 34, 34));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 34, 34));
        jLabel1.setText("Finanças");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTableConsultaOrcamento.setBackground(new java.awt.Color(255, 255, 255));
        jTableConsultaOrcamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Janeiro", "Fevereiro", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultaOrcamento.setAutoscrolls(false);
        jTableConsultaOrcamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableConsultaOrcamento.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTableConsultaOrcamento.setShowGrid(true);
        jScrollPane2.setViewportView(jTableConsultaOrcamento);
        if (jTableConsultaOrcamento.getColumnModel().getColumnCount() > 0) {
            jTableConsultaOrcamento.getColumnModel().getColumn(0).setPreferredWidth(110);
        }

        jButtonExcluir.setBackground(new java.awt.Color(248, 67, 69));
        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setBorder(null);
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExcluir.setPreferredSize(new java.awt.Dimension(150, 65));

        jButtonEditar.setBackground(new java.awt.Color(57, 201, 114));
        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.setBorder(null);
        jButtonEditar.setBorderPainted(false);
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEditar.setFocusPainted(false);
        jButtonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditar.setPreferredSize(new java.awt.Dimension(150, 65));

        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconLupa.png"))); // NOI18N
        jLabelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSearchMousePressed(evt);
            }
        });

        jLabel3.setText("Busca por Ano");

        jTextFieldAno.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y"))));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(320, 320, 320))
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(202, 202, 202))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSearch)))
                        .addGap(62, 62, 62))))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166))
        );

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoRegistro(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoRegistro
         new NovoRegistro().setVisible(true);
    }//GEN-LAST:event_btnNovoRegistro

    private void fecharJanela(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fecharJanela
        
        if(telaChamadoraMainMenu == null){
            new MainMenu().setVisible(true);
        }else{
            telaChamadoraMainMenu.setVisible(true);
        }
                
        
        this.dispose();
    }//GEN-LAST:event_fecharJanela

    private void btnDashboard(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboard
        telaChamadoraMainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboard

    private void jLabelSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMousePressed
        listarTodosOrcamentos(jTextFieldAno.getText());
    }//GEN-LAST:event_jLabelSearchMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         listarTodosOrcamentos();
    }//GEN-LAST:event_formWindowOpened
    
    public void listarTodosOrcamentos(){
        
        DefaultTableModel tabelaOrcamentoModel = (DefaultTableModel) jTableConsultaOrcamento.getModel(); // tabela
        tabelaOrcamentoModel.setRowCount(0);
       
        OrcamentoController oc = new OrcamentoController();
        
       
        ArrayList<Orcamento> orcamentos = null;
        
        try {
            orcamentos = oc.listarOrcamentos();
        } catch (ExceptionDAO ex) {
            java.util.logging.Logger.getLogger(ApresentaFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            
            try {
               orcamentos.forEach((Orcamento orcamento) -> {
                 tabelaOrcamentoModel.addRow(new Object[] {orcamento.getNome(),
                                                        Dinheiro.parseString(orcamento.getJan()),
                                                        Dinheiro.parseString(orcamento.getFev()),
                                                        Dinheiro.parseString(orcamento.getMar()),
                                                        Dinheiro.parseString(orcamento.getAbr()),
                                                        Dinheiro.parseString(orcamento.getMai()),
                                                        Dinheiro.parseString(orcamento.getJun()),
                                                        Dinheiro.parseString(orcamento.getJul()),
                                                        Dinheiro.parseString(orcamento.getAgo()),
                                                        Dinheiro.parseString(orcamento.getSet()),
                                                        Dinheiro.parseString(orcamento.getOut()),
                                                        Dinheiro.parseString(orcamento.getNov()),
                                                        Dinheiro.parseString(orcamento.getDez()),
                                                        Dinheiro.parseString(orcamento.getJan())
                                                        });
            
               });     
               
            SimpleDateFormat df = new SimpleDateFormat("yyyy");
            java.util.Date ano = new java.util.Date();
               
               tabelaOrcamentoModel.addRow(new Object[] {"TOTAL", 
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("JANEIRO",df.format(ano)))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("FEVEREIRO",df.format(ano)))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("MARCO",df.format(ano)))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("ABRIL",df.format(ano)))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("MAIO",df.format(ano)))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("JUNHO",df.format(ano)))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("JULHO",df.format(ano)))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("AGOSTO",df.format(ano)))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("SETEMBRO",df.format(ano)))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("OUTUBRO",df.format(ano)))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("NOVEMBRO",df.format(ano)))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("DEZEMBRO",df.format(ano))))
                               
                                                        });
                
             
         
            jTableConsultaOrcamento.setModel(tabelaOrcamentoModel);
            
            jTableConsultaOrcamento.getColumnModel().getColumn(0).setCellRenderer(new FormatacaoConteudo(Color.WHITE, jTableConsultaOrcamento.getRowCount()-1));
              
               
             
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro ao listarClientes" + e);
            }
    }
    
    public class FormatacaoConteudo extends DefaultTableCellRenderer implements TableCellRenderer {

        
        private Color color;
        private int row = -1;
        
        public FormatacaoConteudo(Color color, int row){
            super();
            this.color = color;
            this.row = row;
	}
     
        @Override
        public Component getTableCellRendererComponent(JTable table, 
                                                        Object value, boolean isSelected, 
                                                        boolean hasFocus, int row, int column) {
            
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if( row != -1 && color != null){
                if( row == this.row){
                    c.setBackground( new Color( 0, 0, 0));
                    c.setForeground(this.color );
                }else{
                   c.setBackground( new Color( 255, 255, 255)); 
                   c.setForeground( new Color(0,0,0) ); 
                } 
            }
           
      
            return c;

        }
    
    }
    
 
    public void listarTodosOrcamentos(String ano){
        
        DefaultTableModel tabelaOrcamentoModel = (DefaultTableModel) jTableConsultaOrcamento.getModel(); // tabela
        tabelaOrcamentoModel.setRowCount(0);
       
        OrcamentoController oc = new OrcamentoController();
        
       
        ArrayList<Orcamento> orcamentos = null;
        
        try {
            orcamentos = oc.listarOrcamentos(ano);
        } catch (ExceptionDAO ex) {
            java.util.logging.Logger.getLogger(ApresentaFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            
            try {
               orcamentos.forEach((Orcamento orcamento) -> {
                 tabelaOrcamentoModel.addRow(new Object[] {orcamento.getNome(),
                                                        Dinheiro.parseString(orcamento.getJan()),
                                                        Dinheiro.parseString(orcamento.getFev()),
                                                        Dinheiro.parseString(orcamento.getMar()),
                                                        Dinheiro.parseString(orcamento.getAbr()),
                                                        Dinheiro.parseString(orcamento.getMai()),
                                                        Dinheiro.parseString(orcamento.getJun()),
                                                        Dinheiro.parseString(orcamento.getJul()),
                                                        Dinheiro.parseString(orcamento.getAgo()),
                                                        Dinheiro.parseString(orcamento.getSet()),
                                                        Dinheiro.parseString(orcamento.getOut()),
                                                        Dinheiro.parseString(orcamento.getNov()),
                                                        Dinheiro.parseString(orcamento.getDez()),
                                                        Dinheiro.parseString(orcamento.getJan())
                                                        });
            
               });
               
         
               
               tabelaOrcamentoModel.addRow(new Object[] {"TOTAL", 
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("JANEIRO", ano ))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("FEVEREIRO", ano))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("MARCO",ano))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("ABRIL",ano))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("MAIO", ano))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("JUNHO", ano))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("JULHO", ano))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("AGOSTO", ano))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("SETEMBRO", ano))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("OUTUBRO", ano))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("NOVEMBRO", ano))),
                                                        Dinheiro.parseString(Dinheiro.parseBigDecimal(oc.somarOrcamento("DEZEMBRO", ano)))
                         
                                                        });
               
               jTableConsultaOrcamento.setModel(tabelaOrcamentoModel);
               
               //Pinta campo total
               jTableConsultaOrcamento.getColumnModel().getColumn(0).setCellRenderer(new FormatacaoConteudo(Color.WHITE, jTableConsultaOrcamento.getRowCount()-1));

                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Erro ao listarClientes" + e);
            }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApresentaFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApresentaFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApresentaFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApresentaFinancas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApresentaFinancas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTFFinancas;
    private javax.swing.JLabel JTFNovoRegistro;
    private javax.swing.JLabel JTFProdutos;
    private javax.swing.JPanel container;
    private javax.swing.JLabel dashboard;
    private javax.swing.JPanel gridLateral;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jTFClientes;
    private javax.swing.JTable jTableConsultaOrcamento;
    private javax.swing.JFormattedTextField jTextFieldAno;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelFinancas;
    private javax.swing.JPanel panelNovoRegistro;
    private javax.swing.JPanel panelProdutos;
    // End of variables declaration//GEN-END:variables
}
