/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BeutifulSalon.view.Edicao;

import BeutifulSalon.Ferramentas.ManipulaFontes;
import BeutifulSalon.controller.OrcamentoController;
import BeutifulSalon.model.OrcamentoServico;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author mateuS
 */
public class EditarOrcamentoServico extends javax.swing.JFrame {

    /**
     * Creates new form EditarOrcamentoServico
     */
    private long idOrcamentoServico;
         
    public EditarOrcamentoServico() {
        initComponents();
        
        ManipulaFontes mf = new ManipulaFontes(); 
        jLabel4.setFont(mf.getFont(mf.MEDIUM, Font.BOLD, 36f)); //Editar Orçamento Previsto de Serviço
        jLabel8.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Identificador
        jLabel7.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Nome do Serviço
        jLabel32.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Exercício (AAAA)

        jCheckBoxFixo1.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Repete
        jLabel31.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Informe a quantidade do serviço selecionado que acredita realizar mensalmente

        jLabel9.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Jan
        jLabel10.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Fev
        jLabel11.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Mar
        jLabel13.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Abril
        jLabel25.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Maio
        jLabel26.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Jun
        jLabel12.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Jul
        jLabel28.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Ago
        jLabel29.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Set
        jLabel9.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Out
        jLabel27.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Nov
        jLabel30.setFont(mf.getFont(mf.MEDIUM, Font.PLAIN, 15f)); //Dez


        btnRegOrcServico.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //Registrar
        btnCanc1.setFont(mf.getFont(mf.BOLD, Font.PLAIN, 15f)); //Cancelar
    }
    
    public EditarOrcamentoServico(OrcamentoServico orcamentoServico) {
        initComponents();
        
        jTextFieldIdServico.setText(String.valueOf(orcamentoServico.getId_servico()));
        jTextFieldNomeServico.setText(orcamentoServico.getNome());
        jTextFieldAnoOrc.setText(orcamentoServico.getAno());
        
        jSpinnerJan.setValue(orcamentoServico.getJan());
        jSpinnerFev.setValue(orcamentoServico.getFev());
        jSpinnerMarc.setValue(orcamentoServico.getMar());
        jSpinnerAbr.setValue(orcamentoServico.getAbr());
        jSpinnerMai.setValue(orcamentoServico.getMai());
        jSpinnerJun.setValue(orcamentoServico.getJun());
        jSpinnerJul.setValue(orcamentoServico.getJul());
        jSpinnerAgo.setValue(orcamentoServico.getAgo());
        jSpinnerSet.setValue(orcamentoServico.getSet());
        jSpinnerOut.setValue(orcamentoServico.getOut());
        jSpinnerNov.setValue(orcamentoServico.getNov());
        jSpinnerDez.setValue(orcamentoServico.getDez());
        
        this.idOrcamentoServico = orcamentoServico.getId_orcamento();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelServicos = new javax.swing.JPanel();
        jTextFieldIdServico = new javax.swing.JTextField();
        jTextFieldNomeServico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSpinnerJan = new javax.swing.JSpinner();
        jSpinnerFev = new javax.swing.JSpinner();
        jSpinnerMarc = new javax.swing.JSpinner();
        jSpinnerAbr = new javax.swing.JSpinner();
        jSpinnerMai = new javax.swing.JSpinner();
        jSpinnerJun = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSpinnerAgo = new javax.swing.JSpinner();
        jSpinnerOut = new javax.swing.JSpinner();
        jSpinnerDez = new javax.swing.JSpinner();
        jSpinnerJul = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinnerSet = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        jSpinnerNov = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        btnCanc1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldAnoOrc = new javax.swing.JFormattedTextField();
        jCheckBoxFixo1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnRegOrcServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelServicos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelServicos.setPreferredSize(new java.awt.Dimension(1200, 650));

        jTextFieldIdServico.setEditable(false);
        jTextFieldIdServico.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldIdServico.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldNomeServico.setEditable(false);
        jTextFieldNomeServico.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeServico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(34, 34, 34));
        jLabel7.setText("Nome do Serviço");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(34, 34, 34));
        jLabel8.setText("Identificador");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jSpinnerJan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerJan.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerJan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSpinnerFev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerFev.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerFev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSpinnerMarc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerMarc.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerMarc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSpinnerAbr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerAbr.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerAbr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSpinnerMai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerMai.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerMai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSpinnerJun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerJun.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerJun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(34, 34, 34));
        jLabel9.setText("Janeiro");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(34, 34, 34));
        jLabel10.setText("Fevereiro");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(34, 34, 34));
        jLabel11.setText("Março");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(34, 34, 34));
        jLabel13.setText("Abril");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(34, 34, 34));
        jLabel25.setText("Maio");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(34, 34, 34));
        jLabel26.setText("Junho");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jSpinnerAgo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerAgo.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerAgo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSpinnerOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerOut.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSpinnerDez.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerDez.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerDez.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSpinnerJul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerJul.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerJul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(34, 34, 34));
        jLabel12.setText("Julho");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(34, 34, 34));
        jLabel14.setText("Setembro");

        jSpinnerSet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerSet.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerSet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(34, 34, 34));
        jLabel27.setText("Novembro");

        jSpinnerNov.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerNov.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(1000L), Long.valueOf(1L)));
        jSpinnerNov.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(34, 34, 34));
        jLabel28.setText("Agosto");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(34, 34, 34));
        jLabel29.setText("Outubro");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(34, 34, 34));
        jLabel30.setText("Dezembro");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSpinnerJul)
                        .addComponent(jSpinnerSet)
                        .addComponent(jSpinnerNov, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSpinnerDez, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(jSpinnerAgo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSpinnerOut, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerJul, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerSet, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerNov, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerAgo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerDez, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSpinnerMai, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(jSpinnerMarc)
                        .addComponent(jSpinnerJan))
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel25))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSpinnerJun, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(jSpinnerFev, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSpinnerAbr, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerFev, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerJan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerMarc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerMai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerAbr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerJun, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnCanc1.setBackground(new java.awt.Color(255, 255, 255));
        btnCanc1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCanc1.setText("Cancelar");
        btnCanc1.setBorder(null);
        btnCanc1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCanc1.setPreferredSize(new java.awt.Dimension(150, 65));
        btnCanc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanc1ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(34, 34, 34));
        jLabel31.setText("Informe a quantidade do serviço selecionado que acredita realizar mensalmente");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(34, 34, 34));
        jLabel32.setText("Exercício (AAAA)");

        jTextFieldAnoOrc.setForeground(new java.awt.Color(34, 34, 34));
        try {
            jTextFieldAnoOrc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldAnoOrc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jCheckBoxFixo1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxFixo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBoxFixo1.setForeground(new java.awt.Color(34, 34, 34));
        jCheckBoxFixo1.setText("Repete");
        jCheckBoxFixo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFixo1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(36, 46, 65));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Editar Orçamento Previsto de Serviço");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-financas-48.png"))); // NOI18N
        jLabel34.setText("jLabel34");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel4))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        btnRegOrcServico.setBackground(new java.awt.Color(255, 255, 255));
        btnRegOrcServico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegOrcServico.setText("Atualizar");
        btnRegOrcServico.setBorder(null);
        btnRegOrcServico.setBorderPainted(false);
        btnRegOrcServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegOrcServico.setPreferredSize(new java.awt.Dimension(150, 65));
        btnRegOrcServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegOrcServicoMousePressed(evt);
            }
        });
        btnRegOrcServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegOrcServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelServicosLayout = new javax.swing.GroupLayout(jPanelServicos);
        jPanelServicos.setLayout(jPanelServicosLayout);
        jPanelServicosLayout.setHorizontalGroup(
            jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelServicosLayout.createSequentialGroup()
                .addGroup(jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelServicosLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnRegOrcServico, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnCanc1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelServicosLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelServicosLayout.createSequentialGroup()
                                .addGroup(jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldIdServico, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(86, 86, 86)
                                .addGroup(jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addGroup(jPanelServicosLayout.createSequentialGroup()
                                        .addComponent(jTextFieldAnoOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jCheckBoxFixo1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel31)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelServicosLayout.setVerticalGroup(
            jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServicosLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIdServico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnoOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxFixo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegOrcServico, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCanc1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanelServicos, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCanc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanc1ActionPerformed

        int opc = JOptionPane.showConfirmDialog(null, "Realmente deseja sair?", "Editar Orçamento Serviço Previsto", JOptionPane.YES_NO_OPTION);

        if (opc == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCanc1ActionPerformed

    private void jCheckBoxFixo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFixo1ActionPerformed

        long valorRepete = Long.parseLong(jSpinnerJan.getValue().toString());
        long valorNominal = 0;
        if (jCheckBoxFixo1.isSelected()) {
            jSpinnerFev.setValue(valorRepete);
            jSpinnerMarc.setValue(valorRepete);
            jSpinnerAbr.setValue(valorRepete);
            jSpinnerMai.setValue(valorRepete);
            jSpinnerJun.setValue(valorRepete);
            jSpinnerJul.setValue(valorRepete);
            jSpinnerAgo.setValue(valorRepete);
            jSpinnerSet.setValue(valorRepete);
            jSpinnerOut.setValue(valorRepete);
            jSpinnerNov.setValue(valorRepete);
            jSpinnerDez.setValue(valorRepete);
        } else {
            jSpinnerFev.setValue(valorNominal);
            jSpinnerMarc.setValue(valorNominal);
            jSpinnerAbr.setValue(valorNominal);
            jSpinnerMai.setValue(valorNominal);
            jSpinnerJun.setValue(valorNominal);
            jSpinnerJul.setValue(valorNominal);
            jSpinnerAgo.setValue(valorNominal);
            jSpinnerSet.setValue(valorNominal);
            jSpinnerOut.setValue(valorNominal);
            jSpinnerNov.setValue(valorNominal);
            jSpinnerDez.setValue(valorNominal);
        }

    }//GEN-LAST:event_jCheckBoxFixo1ActionPerformed

    private void btnRegOrcServicoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegOrcServicoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegOrcServicoMousePressed

    private void btnRegOrcServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegOrcServicoActionPerformed

        boolean sucesso = false;

        try {

            OrcamentoController oc = new OrcamentoController();
            sucesso = oc.atualizarOrcamentoServico(true,
                jTextFieldNomeServico.getText(),
                Long.parseLong(jTextFieldIdServico.getText()),
                Long.parseLong(jSpinnerJan.getValue().toString()),
                Long.parseLong(jSpinnerFev.getValue().toString()),
                Long.parseLong(jSpinnerMarc.getValue().toString()),
                Long.parseLong(jSpinnerAbr.getValue().toString()),
                Long.parseLong(jSpinnerMai.getValue().toString()),
                Long.parseLong(jSpinnerJun.getValue().toString()),
                Long.parseLong(jSpinnerJul.getValue().toString()),
                Long.parseLong(jSpinnerAgo.getValue().toString()),
                Long.parseLong(jSpinnerSet.getValue().toString()),
                Long.parseLong(jSpinnerOut.getValue().toString()),
                Long.parseLong(jSpinnerNov.getValue().toString()),
                Long.parseLong(jSpinnerDez.getValue().toString()),
                jTextFieldAnoOrc.getText(),
                idOrcamentoServico);

            if (sucesso) {
                JOptionPane.showMessageDialog(null, "Atualização realizada com sucesso.");
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao atualizar orçamento. Verifique os dados informados.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Erro no registro: " + e);
        }
    }//GEN-LAST:event_btnRegOrcServicoActionPerformed
    private void limparSpinners() {
        
        long valorNominal = 0;
        jSpinnerJan.setValue(valorNominal);
        jSpinnerFev.setValue(valorNominal);
        jSpinnerMarc.setValue(valorNominal);
        jSpinnerAbr.setValue(valorNominal);
        jSpinnerMai.setValue(valorNominal);
        jSpinnerJun.setValue(valorNominal);
        jSpinnerJul.setValue(valorNominal);
        jSpinnerAgo.setValue(valorNominal);
        jSpinnerSet.setValue(valorNominal);
        jSpinnerOut.setValue(valorNominal);
        jSpinnerNov.setValue(valorNominal);
        jSpinnerDez.setValue(valorNominal);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarOrcamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarOrcamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarOrcamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarOrcamentoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarOrcamentoServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanc1;
    private javax.swing.JButton btnRegOrcServico;
    private javax.swing.JCheckBox jCheckBoxFixo1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelServicos;
    private javax.swing.JSpinner jSpinnerAbr;
    private javax.swing.JSpinner jSpinnerAgo;
    private javax.swing.JSpinner jSpinnerDez;
    private javax.swing.JSpinner jSpinnerFev;
    private javax.swing.JSpinner jSpinnerJan;
    private javax.swing.JSpinner jSpinnerJul;
    private javax.swing.JSpinner jSpinnerJun;
    private javax.swing.JSpinner jSpinnerMai;
    private javax.swing.JSpinner jSpinnerMarc;
    private javax.swing.JSpinner jSpinnerNov;
    private javax.swing.JSpinner jSpinnerOut;
    private javax.swing.JSpinner jSpinnerSet;
    private javax.swing.JFormattedTextField jTextFieldAnoOrc;
    private javax.swing.JTextField jTextFieldIdServico;
    private javax.swing.JTextField jTextFieldNomeServico;
    // End of variables declaration//GEN-END:variables
}
