/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BeutifulSalon.view.Cadastros;

import BeutifulSalon.Ferramentas.RecuperaTabela;
import BeutifulSalon.controller.ServicoController;
import BeutifulSalon.model.Cliente;
import BeutifulSalon.model.Observador;
import BeutifulSalon.model.Orcamento;
import BeutifulSalon.model.Servico;
import BeutifulSalon.view.modais.modalProdutosUtilizados;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
/**
 *
 * @author Visitante
 */
public class CadastroServico extends javax.swing.JFrame implements Observador {
    /**
     * Creates new form CadastroServico
     */
    public CadastroServico() {
        initComponents();
        
        DecimalFormat decimal = new DecimalFormat("#,###,###.00");
        NumberFormatter numFormatter = new NumberFormatter(decimal);
        numFormatter.setFormat(decimal);
        numFormatter.setAllowsInvalid(false);
        DefaultFormatterFactory dfFactory = new DefaultFormatterFactory(numFormatter);
        jFormattedTextFieldPreco1.setFormatterFactory(dfFactory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroServico = new javax.swing.JPanel();
        jLabelPreco = new javax.swing.JLabel();
        jTextFieldNomeServico = new javax.swing.JTextField();
        jLabelTempoGasto = new javax.swing.JLabel();
        jFormattedTextFieldTempoGasto = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMostraProdutos = new javax.swing.JTable();
        jLabelProdutos = new javax.swing.JLabel();
        jLabelBotao = new javax.swing.JLabel();
        jLabelNome2 = new javax.swing.JLabel();
        jFormattedTextFieldPreco1 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanelCadastroServico.setBackground(new java.awt.Color(243, 244, 245));

        jLabelPreco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPreco.setForeground(new java.awt.Color(34, 34, 34));
        jLabelPreco.setText("Preço");

        jTextFieldNomeServico.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldNomeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeServicoActionPerformed(evt);
            }
        });

        jLabelTempoGasto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTempoGasto.setForeground(new java.awt.Color(34, 34, 34));
        jLabelTempoGasto.setText("Tempo gasto");

        try {
            jFormattedTextFieldTempoGasto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTempoGasto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldTempoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTempoGastoActionPerformed(evt);
            }
        });

        jTableMostraProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Marca", "Rendimento", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableMostraProdutos);
        if (jTableMostraProdutos.getColumnModel().getColumnCount() > 0) {
            jTableMostraProdutos.getColumnModel().getColumn(3).setMinWidth(1);
            jTableMostraProdutos.getColumnModel().getColumn(3).setPreferredWidth(1);
            jTableMostraProdutos.getColumnModel().getColumn(3).setMaxWidth(1);
        }

        jLabelProdutos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelProdutos.setForeground(new java.awt.Color(34, 34, 34));
        jLabelProdutos.setText("Produtos Utilizados");

        jLabelBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-add.png"))); // NOI18N
        jLabelBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBotaoMousePressed(evt);
            }
        });

        jLabelNome2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNome2.setForeground(new java.awt.Color(34, 34, 34));
        jLabelNome2.setText("Nome Serviço");

        jFormattedTextFieldPreco1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jFormattedTextFieldPreco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPreco1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(57, 201, 114));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cadastrar");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(150, 65));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(248, 67, 69));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cancelar");
        jButton4.setBorder(null);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setPreferredSize(new java.awt.Dimension(150, 65));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 34, 34));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro Serviço");

        javax.swing.GroupLayout jPanelCadastroServicoLayout = new javax.swing.GroupLayout(jPanelCadastroServico);
        jPanelCadastroServico.setLayout(jPanelCadastroServicoLayout);
        jPanelCadastroServicoLayout.setHorizontalGroup(
            jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroServicoLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                                .addComponent(jTextFieldNomeServico)
                                .addGap(62, 62, 62))
                            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldTempoGasto)
                                .addGap(222, 222, 222))
                            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                                .addComponent(jLabelNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldPreco1))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroServicoLayout.createSequentialGroup()
                        .addComponent(jLabelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                        .addGap(173, 173, 173))
                    .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                        .addComponent(jLabelTempoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelBotao)
                                .addContainerGap(253, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroServicoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56))))))
        );
        jPanelCadastroServicoLayout.setVerticalGroup(
            jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome2)
                    .addComponent(jLabelPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldPreco1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabelTempoGasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldTempoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabelProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCadastroServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadastroServicoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeServicoActionPerformed

    private void jFormattedTextFieldTempoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTempoGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTempoGastoActionPerformed

    private void jLabelBotaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBotaoMousePressed
        modalProdutosUtilizados produtoNovo = new modalProdutosUtilizados();
        produtoNovo.registrarObservador(this);
        produtoNovo.setVisible(true);
    }//GEN-LAST:event_jLabelBotaoMousePressed

    private void jFormattedTextFieldPreco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPreco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPreco1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        boolean sucesso;
        
        ServicoController sv = new ServicoController(); //instanciar o controlador, que recebe um novo controlador
        try {     
            sucesso = sv.cadastrarServico(
                    jTextFieldNomeServico.getText(),
                    jFormattedTextFieldPreco1.getText(),
                    jFormattedTextFieldTempoGasto.getText(),
                    new RecuperaTabela().Produtos(jTableMostraProdutos)
            );

            if (sucesso) {
                JOptionPane.showMessageDialog(null, "Serviço cadastrado com sucesso!");
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Verifique os campos preenhcidos.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CadastroServico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int opc = JOptionPane.showConfirmDialog(null, "Realmente deseja sair?", "Cadastro Servico", JOptionPane.YES_NO_OPTION);

        if (opc == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void limparCampos(){
        jTextFieldNomeServico.setText("");
        jFormattedTextFieldTempoGasto.setText("");
        jFormattedTextFieldPreco1.setText("");
        
        DefaultTableModel model = (DefaultTableModel) jTableMostraProdutos.getModel();
        model.setRowCount(0);
        jTableMostraProdutos.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFormattedTextField jFormattedTextFieldPreco1;
    private javax.swing.JFormattedTextField jFormattedTextFieldTempoGasto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBotao;
    private javax.swing.JLabel jLabelNome2;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelProdutos;
    private javax.swing.JLabel jLabelTempoGasto;
    private javax.swing.JPanel jPanelCadastroServico;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMostraProdutos;
    private javax.swing.JTextField jTextFieldNomeServico;
    // End of variables declaration//GEN-END:variables

   
   

    //pega a tebala da outra tela e recebe nessa
    @Override
    public void update(DefaultTableModel model) {
        jTableMostraProdutos.setModel(model);
    }
    
    @Override
    public void update(Object obj) { }
    
    @Override
    public void update(String valorDesconto) {}
    

    @Override
    public void update(Cliente cliente) {}  
    
    @Override
    public void update(Servico servico) {}

    @Override
    public void update(ArrayList<LocalTime> horarios) {
    }
    
     @Override
    public void update(Orcamento orcamento) {
    
    }
   
}
